### ISSUE TITLE
OpenSSL build fails in Docker container due to missing development headers

### ISSUE THREAD

**Issue by garysassano** [cargo-lambda/cargo-lambda-cdk#72]
When building a Rust Lambda function that depends on OpenSSL (directly or indirectly) using cargo-lambda-cdk, the build fails due to missing OpenSSL development headers in the Docker container. This affects both x86_64 and ARM64 architectures.

## Error Message
```
In file included from build/expando.c:1:
In file included from /usr/include/openssl/opensslv.h:109:
/usr/include/openssl/macros.h:14:10: fatal error: 'openssl/opensslconf.h' file not found
   14 | #include <openssl/opensslconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

Failed to find OpenSSL development headers.
```

## Steps to Reproduce
1. Create a new CDK project using cargo-lambda-cdk
2. Add a dependency that uses OpenSSL. For example, add `reqwest` to `Cargo.toml`:
```toml
[dependencies]
reqwest = "0.11"
```
3. Run `cdk deploy`

## Expected Behavior
The build should succeed with all necessary development headers available in the Docker container.

## Current Behavior
The build fails in the Docker container with the error "Failed to find OpenSSL development headers" when trying to compile `openssl-sys`. This occurs because the Docker image (`ghcr.io/cargo-lambda/cargo-lambda`) lacks the required OpenSSL development headers.

## Proposed Solutions
1. Install OpenSSL development packages in the Docker image:
```dockerfile
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev
```

2. Configure the Docker build process to use vendored OpenSSL by default

## Current Workaround
Users can work around this by enabling the vendored feature for OpenSSL-dependent crates. For example:
```toml
[dependencies]
# For direct OpenSSL usage:
openssl = { version = "0.10", features = ["vendored"] }
# For reqwest:
reqwest = { version = "0.11", features = ["native-tls-vendored"] }
```

## Environment
- cargo-lambda-cdk: 0.0.31
- AWS CDK: 2.170.0
- Docker image: ghcr.io/cargo-lambda/cargo-lambda

## Additional Context
This is a build-time dependency issue in the Docker container and affects all target architectures. The problem occurs during the build phase, not during runtime execution in Lambda. The error is specifically related to missing development headers that are typically provided by the `libssl-dev` package on Debian/Ubuntu-based systems.

**Comment by calavera** [comment]
This is expected, and documented in the [Cross Compilation guide](https://www.cargo-lambda.info/guide/cross-compiling.html#known-cross-compilation-issues). Dynamically linking OpenSSL is not recommended because there are no guarantees that that AWS Lambda sandbox includes the same library version.

If you still need other build dependencies, you need to provide your own Docker image, as [explained in the README](https://github.com/cargo-lambda/cargo-lambda-cdk?tab=readme-ov-file#docker).
